env_type: "local"
  
jwt:
  private_key_path: "./keys/private_key.pem"
  public_key_path: "./keys/public_key.pem"
  token_ttl: 24h

storage:
  url: "mongodb://mongodb:27017"
  username: "root"
  password: "passwordXD_1234"
  db_name: "local"

server:
  port: 8000
