services:
  # nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backbone
    depends_on:
      - users

  # Our code
  users:
    container_name: users
    build:
      context: ./users
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - mongo
    environment:
      - ENV_TYPE=dev
    networks:
      - backbone
  
  news:
    container_name: news
    build:
      context: ./news
    ports:
      - "8001:8000"
    expose:
      - 8000
    depends_on:
      - postgres
    # env_file:
    #   - 
    networks:
      - backbone
  
  
  # databases
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: local
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordXD_1234
    ports:
      - 27017:27017
  
  postgres:
    build:
      context: ./postgres 
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwordXD_1234
      POSTGRES_DB: local
    ports:
      - 5432:5432


networks:
  backbone:
    driver: bridge
