# Generated by Django 4.2.11 on 2024-04-20 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('website_url', models.CharField(max_length=256)),
                ('deputy_id', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='UserToGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('group_id', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_to_group',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('students_count', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='universities.departmentmodel')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='universities.universitymodel'),
        ),
    ]
