# Generated by Django 4.2.11 on 2024-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
