# Generated by Django 4.2.11 on 2024-04-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_groupmodel_students_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertogroupmodel',
            name='user_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
