# Generated by Django 4.2.11 on 2024-04-20 11:20

import api.universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_usertogroupmodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.IntegerField(verbose_name='Id университета')),
                ('image', models.ImageField(max_length=512, upload_to=api.universities.models.university_image_upload_path, verbose_name='Изображение')),
            ],
            options={
                'db_table': 'university_image',
            },
        ),
    ]
