openapi: 3.0.0
info:
  title: Template API
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created
        '400':
          description: Bad request
        '500':
          description: Server error
  /login:
    post:
      summary: Login user
      responses:
        '200':
          description: User logged info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Bad request
        '404':
          description: User not found
        '500':
          description: Server error

components:
  schemas:
    Token:
      type: object
      properties:
        token:
          type: string
    
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        repeat_password:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

