from .department import DepartmentController, DepartmentsController, SearchDepartmentController
from .group import GroupController, GroupsController, SearchGroupController
from .university import UniversityController, UniversitiesController, UniversitySearchController, DeputyUniversityController
