# Generated by Django 4.2.11 on 2024-04-19 16:57

import api.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikesToPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Id пользователя')),
                ('post_id', models.IntegerField(verbose_name='Id поста')),
            ],
            options={
                'verbose_name': 'Лайки к постам',
                'db_table': 'like_to_post',
            },
        ),
        migrations.CreateModel(
            name='PostImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(verbose_name='Id поста')),
                ('image', models.ImageField(max_length=512, upload_to=api.posts.models.post_image_upload_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Лайки к постам',
                'db_table': 'post_image',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('author_id', models.IntegerField(verbose_name='Id автора')),
                ('likes', models.IntegerField(default=0, verbose_name='Кол-во лайков')),
            ],
            options={
                'verbose_name': 'Пост',
                'db_table': 'post',
            },
        ),
    ]
