# Generated by Django 4.2.11 on 2024-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likestopostmodel',
            name='user_id',
            field=models.CharField(verbose_name='Id пользователя'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author_id',
            field=models.CharField(verbose_name='Id автора'),
        ),
    ]
