# Generated by Django 4.2.11 on 2024-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_likestopostmodel_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
