# Generated by Django 4.2.11 on 2024-04-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_at',
            field=models.CharField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
