# Generated by Django 4.2.11 on 2024-04-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_hashtag_postmodel_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(verbose_name='Id пользователя')),
                ('user_id', models.CharField(max_length=128, verbose_name='Id пользователя')),
                ('comment', models.CharField(max_length=1024, verbose_name='Комментарий')),
                ('created_at', models.CharField(blank=True, max_length=128, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'db_table': 'comment',
            },
        ),
        migrations.AlterField(
            model_name='likestopostmodel',
            name='user_id',
            field=models.CharField(max_length=128, verbose_name='Id пользователя'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author_id',
            field=models.CharField(max_length=128, verbose_name='Id автора'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='created_at',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Дата создания'),
        ),
    ]
